import type { Metadata } from "next";
import "./globals.css";
import LangPlayerButton from "./components/menu/lang-playerbutton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col overflow-hidden">
        <header className="absolute w-screen top-0 z-50">
          <LangPlayerButton />
        </header>
        {children}
      </body>
    </html>
  );
}
